{"name": "Verify Get Request Status Code", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n  +404\n  -400", "trace": "self = <data_driven_test.test_data_driven.Test_DDT_URL object at 0x000001CD42BAF430>, url = 'http://supplant.me/bot', expected_status_code = '400'\n\n    @allure.title(\"Verify Get Request Status Code\")\n    @allure.description(\"This test verify that the request passed successfully\")\n    @pytest.mark.parametrize(keys, values)\n    def test_status_code(self, url, expected_status_code):\n        response = requests.get(url)\n>       assert response.status_code == int(expected_status_code)\nE       assert 404 == 400\nE         +404\nE         -400\n\ndata_driven_test\\test_data_driven.py:17: AssertionError"}, "description": "This test verify that the request passed successfully", "parameters": [{"name": "url", "value": "'http://supplant.me/bot'"}, {"name": "expected_status_code", "value": "'400'"}], "start": 1651389314248, "stop": 1651389315612, "uuid": "dc564343-c111-40bc-97f4-4a3880853e46", "historyId": "90a8163204cbd34c7e611ecef4007fdb", "testCaseId": "55499a46d297655c67691cd3888cc7f1", "fullName": "data_driven_test.test_data_driven.Test_DDT_URL#test_status_code", "labels": [{"name": "parentSuite", "value": "data_driven_test"}, {"name": "suite", "value": "test_data_driven"}, {"name": "subSuite", "value": "Test_DDT_URL"}, {"name": "host", "value": "AlexK-Dell"}, {"name": "thread", "value": "19472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "data_driven_test.test_data_driven"}]}